//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TaiKhoanNV
    {

        [DisplayName("Account")]
        public string TenTaiKhoan { get; set; }

        [DisplayName("Password")]
        public string MatKhau { get; set; }

        [DisplayName("Privilege")]
        public byte Quyen { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
